const ABILITIES: string[] = ['Adaptability',
   'Aerilate',
   'Aftermath',
   'Air Lock',
   'Anger Point',
   'Anger Shell',
   'Anticipation',
   'Arena Trap',
   'Armor Tail',
   'Aroma Veil',
   'As One',
   'Aura Break',
   'Bad Dreams',
   'Ball Fetch',
   'Battery',
   'Battle Armor',
   'Battle Bond',
   'Beads of Ruin',
   'Beast Boost',
   'Berserk',
   'Big Pecks',
   'Blaze',
   'Bulletproof',
   'Cheek Pouch',
   'Chilling Neigh',
   'Chlorophyll',
   'Clear Body',
   'Cloud Nine',
   'Color Change',
   'Comatose',
   'Commander',
   'Competitive',
   'Compound Eyes',
   'Contrary',
   'Corrosion',
   'Cotton Down',
   'Cud Chew',
   'Curious Medicine',
   'Cursed Body',
   'Cute Charm',
   'Damp',
   'Dancer',
   'Dark Aura',
   'Dauntless Shield',
   'Dazzling',
   'Defeatist',
   'Defiant',
   'Delta Stream',
   'Desolate Land',
   'Disguise',
   'Download',
   'Dragon’s Maw',
   'Drizzle',
   'Drought',
   'Dry Skin',
   'Early Bird',
   'Earth Eater',
   'Effect Spore',
   'Electric Surge',
   'Electromorphosis',
   'Emergency Exit',
   'Fairy Aura',
   'Filter',
   'Flame Body',
   'Flash Fire',
   'Flower Gift',
   'Flower Veil',
   'Fluffy',
   'Forecast',
   'Forewarn',
   'Friend Guard',
   'Frisk',
   'Full Metal Body',
   'Fur Coat',
   'Gluttony',
   'Good as Gold',
   'Gooey',
   'Gorilla Tactics',
   'Grassy Surge',
   'Grim Neigh',
   'Guard Dog',
   'Gulp Missile',
   'Guts',
   'Hadron Engine',
   'Healer',
   'Heatproof',
   'Heavy Metal',
   'Honey Gather',
   'Hospitality',
   'Huge Power',
   'Hunger Switch',
   'Hustle',
   'Hydration',
   'Hyper Cutter',
   'Ice Body',
   'Ice Face',
   'Illuminate',
   'Illusion',
   'Immunity',
   'Infiltrator',
   'Innards Out',
   'Inner Focus',
   'Insomnia',
   'Intimidate',
   'Intrepid Sword',
   'Iron Barbs',
   'Iron Fist',
   'Justified',
   'Keen Eye',
   'Klutz',
   'Leaf Guard',
   'Levitate',
   'Light Metal',
   'Lightning Rod',
   'Limber',
   'Lingering Aroma',
   'Liquid Ooze',
   'Magic Bounce',
   'Magic Guard',
   'Magician',
   'Magma Armor',
   'Magnet Pull',
   'Marvel Scale',
   'Mega Launcher',
   'Merciless',
   'Mimicry',
   'Mind’s Eye',
   'Minus',
   'Misty Surge',
   'Mold Breaker',
   'Motor Drive',
   'Moxie',
   'Multitype',
   'Mummy',
   'Mycelium Might',
   'Natural Cure',
   'Neuroforce',
   'Neutralizing Gas',
   'No Guard',
   'Normalize',
   'Oblivious',
   'Opportunist',
   'Orichalcum Pulse',
   'Overcoat',
   'Overgrow',
   'Own Tempo',
   'Parental Bond',
   'Pastel Veil',
   'Pickpocket',
   'Pickup',
   'Pixilate',
   'Plus',
   'Poison Heal',
   'Poison Point',
   'Poison Puppeteer',
   'Poison Touch',
   'Power Construct',
   'Power Spot',
   'Prankster',
   'Pressure',
   'Primordial Sea',
   'Prism Armor',
   'Protosynthesis',
   'Psychic Surge',
   'Punk Rock',
   'Pure Power',
   'Purifying Salt',
   'Quark Drive',
   'Queenly Majesty',
   'Quick Draw',
   'Quick Feet',
   'RKS System',
   'Rain Dish',
   'Rattled',
   'Receiver',
   'Reckless',
   'Refrigerate',
   'Regenerator',
   'Ripen',
   'Rivalry',
   'Rock Head',
   'Rough Skin',
   'Run Away',
   'Sand Force',
   'Sand Rush',
   'Sand Spit',
   'Sand Stream',
   'Sand Veil',
   'Sap Sipper',
   'Schooling',
   'Scrappy',
   'Screen Cleaner',
   'Seed Sower',
   'Serene Grace',
   'Shadow Shield',
   'Shadow Tag',
   'Sharpness',
   'Shed Skin',
   'Sheer Force',
   'Shell Armor',
   'Shield Dust',
   'Shields Down',
   'Simple',
   'Skill Link',
   'Slow Start',
   'Slush Rush',
   'Sniper',
   'Snow Cloak',
   'Snow Warning',
   'Solar Power',
   'Solid Rock',
   'Soul-Heart',
   'Soundproof',
   'Speed Boost',
   'Stakeout',
   'Stall',
   'Stamina',
   'Stance Change',
   'Static',
   'Steadfast',
   'Steam Engine',
   'Steelworker',
   'Stench',
   'Sticky Hold',
   'Storm Drain',
   'Strong Jaw',
   'Sturdy',
   'Suction Cups',
   'Super Luck',
   'Supersweet Syrup',
   'Supreme Overlord',
   'Surge Surfer',
   'Swarm',
   'Sweet Veil',
   'Swift Swim',
   'Sword of Ruin',
   'Synchronize',
   'Tablets of Ruin',
   'Tangled Feet',
   'Tangling Hair',
   'Technician',
   'Telepathy',
   'Tera Shell',
   'Tera Shift',
   'Teraform Zero',
   'Teravolt',
   'Thermal Exchange',
   'Thick Fat',
   'Tinted Lens',
   'Torrent',
   'Tough Claws',
   'Toxic Chain',
   'Toxic Debris',
   'Trace',
   'Transistor',
   'Triage',
   'Truant',
   'Turboblaze',
   'Unaware',
   'Unburden',
   'Unnerve',
   'Unseen Fist',
   'Vessel of Ruin',
   'Victory Star',
   'Vital Spirit',
   'Volt Absorb',
   'Wandering Spirit',
   'Water Absorb',
   'Water Bubble',
   'Water Compaction',
   'Water Veil',
   'Weak Armor',
   'Well-Baked Body',
   'White Smoke',
   'Wimp Out',
   'Wind Power',
   'Wind Rider',
   'Wonder Guard',
   'Wonder Skin',
   'Zero to Hero'
];

export default ABILITIES;